language: c++
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev libssl-dev libboost-program-options-dev valgrind
script:
  - cmake .
  - make
  - ctest --verbose
compiler: gcc

